<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">

    <style>
        @page {
            margin: 22px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #222;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
        }

        .subtitle {
            font-size: 15px;
            margin-top: 3px;
        }

        .info {
            width: 100%;
            margin-bottom: 15px;
        }

        .info td {
            padding: 4px 2px;
        }

        .label {
            width: 150px;
            font-weight: bold;
        }

        .count-box {
            text-align: right;
            margin-bottom: 10px;
            font-weight: bold;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background: #ececec;
            border: 1px solid #000;
            padding: 7px;
        }

        td {
            border: 1px solid #000;
            padding: 7px;
        }

        .center {
            text-align: center;
        }

        .footer {
            margin-top: 50px;
        }

        .signature {
            width: 45%;
            display: inline-block;
            text-align: center;
        }

        .line {
            border-top: 1px solid #000;
            margin-top: 35px;
            padding-top: 4px;
        }

        .generated {
            text-align: right;
            font-size: 10px;
            margin-top: 15px;
            color: #555;
        }
    </style>

</head>

<body>

    <div class="header">

        <div class="title">
            EXAM CENTER MANAGEMENT SYSTEM
        </div>

        <div class="subtitle">
            ABSENT CANDIDATES REPORT
        </div>

    </div>

    @php
        $first = $absentees->first();
    @endphp

    <table class="info">

        <tr>
            <td class="label">Center Number</td>
            <td>: {{ $first->center_no }}</td>

            <td class="label">Date</td>
            <td>: {{ \Carbon\Carbon::parse($first->date)->format('d F Y') }}</td>
        </tr>

        <tr>
            <td class="label">Session</td>
            <td>: {{ $first->session }}</td>

            <td class="label">Subject Code</td>
            <td>: {{ $first->subject_code }}</td>
        </tr>

        <tr>
            <td class="label">Paper Code</td>
            <td>: {{ $first->paper_code }}</td>

            <td class="label">Generated By</td>
            <td>: {{ Auth::user()->name }}</td>
        </tr>

    </table>

    <div class="count-box">
        Total Absent Candidates : {{ $absentees->count() }}
    </div>

    <table>

        <thead>

            <tr>
                <th width="8%">No</th>
                <th>Index Number</th>
            </tr>

        </thead>

        <tbody>

            @foreach($absentees as $key => $absent)

                <tr>

                    <td class="center">
                        {{ $key + 1 }}
                    </td>

                    <td>
                        {{ $absent->index_no }}
                    </td>

                </tr>

            @endforeach

        </tbody>

    </table>

    <div class="footer">

        <div class="signature">

            <div class="line">
                Prepared By
            </div>

        </div>

        <div style="float:right;" class="signature">

            <div class="line">
                Center Superintendent
            </div>

        </div>

    </div>

    <div class="generated">
        Generated on {{ now()->format('d M Y h:i A') }}
    </div>

</body>

</html>
