<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Special Notes Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #000;
            margin: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
        }

        .title {
            font-size: 20px;
            font-weight: bold;
        }

        .subtitle {
            font-size: 15px;
            font-weight: bold;
            margin-top: 4px;
        }

        .info {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        .info td {
            border: none;
            padding: 4px 6px;
            font-size: 11px;
        }

        .label {
            font-weight: bold;
            width: 18%;
        }

        .report {
            width: 100%;
            border-collapse: collapse;
        }

        .report th,
        .report td {
            border: 1px solid #000;
            padding: 6px;
            text-align: center;
        }

        .report th {
            background: #d9d9d9;
            font-weight: bold;
        }

        .signature-table {
            width: 100%;
            margin-top: 70px;
            border: none;
        }

        .signature-table td {
            border: none;
            text-align: center;
            vertical-align: top;
        }

        .signature-line {
            display: inline-block;
            width: 180px;
            border-top: 1px solid #000;
            padding-top: 5px;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: right;
        }

        @font-face {
            font-family: 'NotoSinhala';
            font-style: normal;
            font-weight: normal;
            src: url("{{ public_path('fonts/NotoSansSinhala-Regular.ttf') }}") format("truetype");
        }

        .message {
            font-family: 'NotoSinhala';
        }
    </style>

</head>

<body>

    <div class="header">

        <div class="title">
            EXAM CENTER MANAGEMENT SYSTEM
        </div>

        <div class="subtitle">
            SPECIAL NOTES REPORT
        </div>

    </div>

    @php

        $first = $comments->first();

    @endphp

    @if ($first)
        <table class="info">

            <tr>

                <td class="label">Center Number</td>
                <td>: {{ $first->center_no }}</td>

                <td class="label">Date</td>
                <td>: {{ \Carbon\Carbon::parse($first->date)->format('d F Y') }}</td>

            </tr>

            <tr>

                <td class="label">Session</td>
                <td>: {{ $first->session }}</td>

                <td class="label">Subject Code</td>
                <td>: {{ $first->subject_code }}</td>

            </tr>

            <tr>

                <td class="label">Paper Code</td>
                <td>: {{ $first->paper_code }}</td>

                <td class="label">Generated By</td>
                <td>: {{ Auth::user()->name }}</td>

            </tr>

            <tr>

                <td class="label">Total Records</td>
                <td>: {{ $comments->count() }}</td>

                <td></td>
                <td></td>

            </tr>

        </table>
    @endif

    <table class="report">

        <thead>

            <tr>

                <th>#</th>
                <th>Center</th>
                <th>Date</th>
                <th>Session</th>
                <th>Subject</th>
                <th>Paper</th>
                <th>Message</th>

            </tr>

        </thead>

        <tbody>

            @forelse($comments as $key => $comment)
                <tr>

                    <td>{{ $key + 1 }}</td>

                    <td>{{ $comment->center_no }}</td>

                    <td>{{ \Carbon\Carbon::parse($comment->date)->format('d-m-Y') }}</td>

                    <td>{{ $comment->session }}</td>

                    <td>{{ $comment->subject_code }}</td>

                    <td>{{ $comment->paper_code }}</td>

                    <td>
                        @if (preg_match('/[\x{0D80}-\x{0DFF}]/u', $comment->message))
                            <span class="message">{{ $comment->message }}</span>
                        @else
                            {{ $comment->message }}
                        @endif
                    </td>

                </tr>

            @empty

                <tr>

                    <td colspan="9">
                        No Special Notes Found
                    </td>

                </tr>
            @endforelse

        </tbody>

    </table>

    <table class="signature-table">

        <tr>

            <td width="33%">

                <span class="signature-line">
                    Prepared By
                </span>
                <br><br>

                {{-- {{ Auth::user()->name }} --}}

            </td>

            <td width="33%">

                <span class="signature-line">
                    Checked By
                </span>

            </td>

            <td width="34%">

                <span class="signature-line">
                    Center Superintendent
                </span>

            </td>

        </tr>

    </table>

    <div class="footer">

        {{-- <strong>Generated By :</strong> {{ Auth::user()->name }}<br> --}}

        <strong>Generated On :</strong>
        {{ now()->format('d F Y h:i A') }}

    </div>

</body>

</html>
